/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author mateo
 */
public class MainHamming extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainHamming() {
               setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        CompactB = new javax.swing.JButton();
        DescB = new javax.swing.JButton();
        tituloHuffman = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 102, 102));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(0, 102, 102));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CompactB.setBackground(new java.awt.Color(0, 153, 153));
        CompactB.setFont(new java.awt.Font("OCR A Extended", 0, 26)); // NOI18N
        CompactB.setForeground(new java.awt.Color(255, 255, 255));
        CompactB.setText("Proteger un archivo");
        CompactB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CompactB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CompactB.setMaximumSize(new java.awt.Dimension(336, 36));
        CompactB.setMinimumSize(new java.awt.Dimension(336, 36));
        CompactB.setPreferredSize(new java.awt.Dimension(336, 36));
        CompactB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompactBMouseClicked(evt);
            }
        });
        CompactB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactBActionPerformed(evt);
            }
        });

        DescB.setBackground(new java.awt.Color(0, 153, 153));
        DescB.setFont(new java.awt.Font("OCR A Extended", 0, 26)); // NOI18N
        DescB.setForeground(new java.awt.Color(255, 255, 255));
        DescB.setText("Desproteger un archivo");
        DescB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DescB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DescB.setMaximumSize(new java.awt.Dimension(336, 36));
        DescB.setMinimumSize(new java.awt.Dimension(336, 36));
        DescB.setPreferredSize(new java.awt.Dimension(336, 36));
        DescB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescBMouseClicked(evt);
            }
        });
        DescB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescBActionPerformed(evt);
            }
        });

        tituloHuffman.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        tituloHuffman.setForeground(new java.awt.Color(218, 236, 255));
        tituloHuffman.setText("Hamming");
        tituloHuffman.setToolTipText("");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(tituloHuffman)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(tituloHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 460, 270));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 1070, 460));

        exitB.setBackground(new java.awt.Color(0, 102, 102));
        exitB.setFont(new java.awt.Font("OCR A Extended", 2, 20)); // NOI18N
        exitB.setForeground(new java.awt.Color(255, 255, 255));
        exitB.setText("SALIR");
        exitB.setAlignmentY(0.0F);
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 90, 30));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Teoría de la Información y la Comunicación");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 510, -1));

        volver.setBackground(new java.awt.Color(0, 102, 102));
        volver.setFont(new java.awt.Font("OCR A Extended", 2, 20)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompactBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompactBMouseClicked

    }//GEN-LAST:event_CompactBMouseClicked

    private void CompactBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactBActionPerformed
        ProtegerHamming c = new ProtegerHamming();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CompactBActionPerformed

    private void DescBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescBMouseClicked
        // TODO add your handling code here:
        DescFrame c = new DescFrame();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescBMouseClicked

    private void DescBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescBActionPerformed
      DesprotegerHamming c = new DesprotegerHamming();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescBActionPerformed

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        MainHyH m = new MainHyH();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompactB;
    private javax.swing.JButton DescB;
    private javax.swing.JPanel background;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel tituloHuffman;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
