/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Usuario
 */
public class mainHuff extends javax.swing.JFrame {

    /**
     * Creates new form mainHuff
     */
    public mainHuff() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        CompactB = new javax.swing.JButton();
        DescB = new javax.swing.JButton();
        tituloHuffman = new javax.swing.JLabel();
        exitB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(0, 102, 102));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(0, 102, 102));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CompactB.setBackground(new java.awt.Color(0, 153, 153));
        CompactB.setFont(new java.awt.Font("OCR A Extended", 0, 26)); // NOI18N
        CompactB.setForeground(new java.awt.Color(255, 255, 255));
        CompactB.setText("COMPACTAR UN ARCHIVO");
        CompactB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CompactB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompactB.setMaximumSize(new java.awt.Dimension(336, 36));
        CompactB.setMinimumSize(new java.awt.Dimension(336, 36));
        CompactB.setPreferredSize(new java.awt.Dimension(336, 36));
        CompactB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompactBMouseClicked(evt);
            }
        });
        CompactB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactBActionPerformed(evt);
            }
        });

        DescB.setBackground(new java.awt.Color(0, 153, 153));
        DescB.setFont(new java.awt.Font("OCR A Extended", 0, 26)); // NOI18N
        DescB.setForeground(new java.awt.Color(255, 255, 255));
        DescB.setText("DESCOMPACTAR UN ARCHIVO");
        DescB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DescB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DescB.setMaximumSize(new java.awt.Dimension(336, 36));
        DescB.setMinimumSize(new java.awt.Dimension(336, 36));
        DescB.setPreferredSize(new java.awt.Dimension(336, 36));
        DescB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescBMouseClicked(evt);
            }
        });
        DescB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescBActionPerformed(evt);
            }
        });

        tituloHuffman.setFont(new java.awt.Font("OCR A Extended", 1, 60)); // NOI18N
        tituloHuffman.setForeground(new java.awt.Color(218, 236, 255));
        tituloHuffman.setText("HUFFMAN");
        tituloHuffman.setToolTipText("");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(tituloHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(tituloHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(CompactB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(DescB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 460, 370));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 1070, 460));

        exitB.setBackground(new java.awt.Color(0, 102, 102));
        exitB.setFont(new java.awt.Font("OCR A Extended", 2, 20)); // NOI18N
        exitB.setForeground(new java.awt.Color(255, 255, 255));
        exitB.setText("SALIR");
        exitB.setAlignmentY(0.0F);
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });
        background.add(exitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 90, 30));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Villalva Mateo y Valdeon Valentin");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 490, 40));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Tecnologia de la Informacion y la Comunicacion");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 510, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompactBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompactBMouseClicked
       
    }//GEN-LAST:event_CompactBMouseClicked

    private void CompactBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactBActionPerformed
        CompactFrame c = new CompactFrame();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CompactBActionPerformed

    private void DescBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescBMouseClicked
        // TODO add your handling code here:
       DescFrame c = new DescFrame();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DescBMouseClicked

    private void DescBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescBActionPerformed

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainHuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainHuff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompactB;
    private javax.swing.JButton DescB;
    private javax.swing.JPanel background;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel tituloHuffman;
    // End of variables declaration//GEN-END:variables
}
